name: Build and Test ScreenPipe

on: [push]
jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Rust
        run: |
          Invoke-WebRequest https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe -OutFile rustup-init.exe
          .\rustup-init.exe -y

      - name: Install 7zip
        shell: powershell
        run: |
          $7zipUrl = "https://7-zip.org/a/7z2301-x64.exe"
          $7zipInstaller = "7z-installer.exe"
          Invoke-WebRequest -Uri $7zipUrl -OutFile $7zipInstaller
          Start-Process -FilePath .\$7zipInstaller -Args "/S" -Wait
          Remove-Item $7zipInstaller
          # Add 7zip to PATH and make it persistent for subsequent steps
          echo "C:\Program Files\7-Zip" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          # Verify installation
          & "C:\Program Files\7-Zip\7z.exe" i

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "10.0"

      - name: Build ScreenPipe
        run: cargo build --release
    
      - name: Upload finished AppImage as artifact (even if previous steps fail)
        uses: actions/upload-artifact@v4.6.0
        if: always() 
        continue-on-error: true
        with:
          name: screenpipe-bundle
          path: target/release/screenpipe.exe
          
         

 
